version: "3"

services:
  db:
    image: "postgres:9.6"
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "54320:5432"

  app:
    depends_on:
      - "db"
    build: .
    command: bash start.sh
    ports:
      - "3000:3000"
    volumes:
      - .:/onebitexchange
      - gems:/gems
    environment:
      - EDITOR=vim


volumes:
  postgres:
  gems:
